config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  get 'contacts/create'

  root :to => 'pages#home'
  
  get 'home' => 'pages#home'

  get 'about' => 'pages#about'

  get 'program' => 'pages#program'

  get 'join' => 'pages#join'

  get 'contact' => 'pages#contact'
  
  post 'send_application' => 'pages#send_application_form'
  
  post 'send_message' => 'pages#send_message_form'

end

app/models/application.rb
class Application < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :intro_about_yourself,     :validate => true
  attribute :personal_website_or_profile
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Application from Xiaoshu Website",
      :to => "mayijun1203@live.cn",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/message.rb
class Message < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Message from Xiaoshu Website",
      :to => "mayijun1203@live.cn",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page = 'home'
  end

  def about
    @page = 'about'
  end

  def program
    @page = 'program'
  end
  
  def join
    @application_sent = false
    @page = 'join'
    @application = Application.new
  end

  def contact
    @message_sent = false
    @page = 'contact'
    @message = Message.new
  end
  
  def send_application_form
    @application = Application.new(params[:application])
    if @application.deliver
      @application_sent = true
      render :join
    else
      flash.now[:error] = 'Cannot send message.'
      render :join
    end
  end
  
  def send_message_form
    @message = Message.new(params[:message])
    if @message.deliver
      @message_sent = true
      render :contact
    else
      flash.now[:error] = 'Cannot send message.'
      render :contact
    end
  end
  
  
  private
  def check_page page
    if @page == page
      return 'selected'
    else
      return ''
    end
  end
  
  helper_method :check_page
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= yield :css %>
  <title>XiaoShu</title>
</head>
<body>
  <header class="navbar navbar-static-top" id="top-nav">
    <div id="navbar-container" class="container-fluid">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#xs-navbar" aria-controls="xs-navbar" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%=link_to image_tag("xiaoshulogo.png" ,:id => "xs-logo", :alt => "XiaoShu logo"), '/', :class => 'navbar-brand' %>
      </div>
      <nav id="xs-navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%=link_to 'HOME', '/', :class => (check_page 'home') %>
          </li>
          <li>
            <%=link_to 'ABOUT', 'about', :id => 'nav-about', :class => (check_page 'about') %>
          </li>
          <li>
            <%=link_to 'PROGRAM', 'program', :id => 'nav-program', :class => (check_page 'program') %>
          </li>
          <li>
            <%=link_to 'JOIN US', 'join', :id => 'nav-join', :class => (check_page 'join') %>
          </li>
          <li>
            <%=link_to 'CONTACT', 'contact', :id => 'nav-contact', :class => (check_page 'contact') %>
          </li>
        </ul>
      </nav>
    </div>
  </header>
<%= yield %>
  <footer id="footer">
    <div class="container">
      <div id="stay-connected" class="col-xs-12 col-md-3">STAY CONNECTED</div>
      <div id="wechat" class="social-media col-xs-12 col-md-3"><%= image_tag("wechat.png",:id => "wechat-logo", :class => 'social-logo') %> WeChat</div>
      <div id="weibo" class="social-media col-xs-12 col-md-3"><%= image_tag("weibo.png",:id => "weibo-logo", :class => 'social-logo') %> Weibo</div>
      <div id="facebook" class="social-media col-xs-12 col-md-3"><%= image_tag("fb.png",:id => "fb-logo", :class => 'social-logo') %> Facebook</div>
      <div id="credit" class="col-xs-12">©2015 XiaoShu | Designed & Developed by <a href="http://www.chenbinyan.com">Binyan Chen</a></div>
    </div>  
  </footer>

<%= javascript_include_tag 'application' %>
<script type="text/javascript">
$(document).ready(function(){
  $('.full-height').height($(window).height());
  //$('.active-bg').css('background-size','auto '+$(window).height()+'px');
  //$.stellar({horizontalScrolling:false,verticalOffset:40});
  
  $('.gallery-photo').each(function(i,obj){
    var image_str = $(this).attr('image');
    var image_url = $("#"+image_str).attr('src');
    $(this).css('background-image', 'url('+image_url+')');
  });
  
  $(window).resize(function(){
    $('.full-height').height($(window).height());
    // //$('.active-bg').css('background-size','auto '+$(window).height()+'px');
  });
  //
  
  $('#scrolldown').click(function(e){
    $('html, body').animate({scrollTop:($(window).height()-60)}, 1000, 'swing');
  });

});
</script>

</body>
</html>

app/views/pages/about.html.erb
<% content_for :css do %>

<% end %>

<div id="content">
  <div id="about-bg" data-parallax="scroll" data-image-src="<%= asset_path('aboutbg.jpg')%>" >
    <div class="container page-caption-container"> 
      <div class="caption-content">
        <div id="about-title-container" class="page-title-container">
          <p class="page-title">ONCE UPON A TIME</p>
        </div>
      </div>
    </div>
  </div>
  <div class="page-content-section container">
    <h1>Our story</h1>
    <p>We started this in 2011, when Toro, a graduate student of Fudan University, became a teacher at Pingfeng Junior Middle School in Ningxia Province, one of the poorest places in China. During that year, we came up to know the real "Chinese style" poverty, with people lacking both in substantial and soft power. However, children there still own beautiful minds despite their poverty. After I saw photos taken by Toro, it occurred to me that I could sponsor a child by reduce some of my daily expenses and saving a portion of my payments as an intern. Then, I informed Toro about my idea and gained support from him. To accomplish this, we opened bank accounts and began to send money, with all of our genuineness and hopefulness. Otherwise, as an intern in an NGO in Shanghai for more than 2 years, I knew what they need is not only material support but also love and concern from the society. Therefore, I decided to write to that girl, hoping that we can establish a relationship, just like friends. When I first read the letter from LP (pseudonym), I couldn't even help crying though I was surrounded by dozens of people in subway. I teared because behind the naive writing skill, these characters suggested maturity a living pressure far beyond her age, indicating enormous burdens on her shoulder, which should never, ever, belong to such a child like her. I suddenly feel so embarrassed by my effeminate compared to my little LP’s maturity and planned to share some burdens for her, and them. Just fight for our future and grow up together!
    </p>
    <p>I always shared some news from LP with my friends and most of them thought this meaningful and joined me. In April 2012, we, together as a team of eight people, went to Pingfeng Middle School in Ningxia Province and visited LP in order to get a more specified view of her and her life there. Although it cost us two days in road by switching from flight to province-to province shoreline(kind of like greyhound in U.S.A) to bus to cars, that was still a definitely valueless trip and made us feel more unswerving on pursuing our little career and dream. We saw what is the real poverty in China; we saw the children’s eyes full of curiosity of the world outside the mountain there, we saw dreams there, not only from them but also from us. Based on this belief, we established Xiaoshu's website, through which we learn about each others' perspiration and persistence. People all over the world, thus attracting more, including you, meanwhile, can see our belief and effort, to join us. And as an encouragement, I promised my children under my sponsorship there that I would return back to be companion with them when they take their life important issue, the National University Entrance Examination, three years later. 
    </p>
    <p>Time is flying fast. Three year later, I was a second-year CIPA fellow in Cornell Universities in U.S.A. During the three years, I kept in deep touch with my child and saw her growing up through letters and phone call. I missed her so much to see her growth directly by my eyes. And I have developed more sponsorship to lead resources there. Finally, to accomplish my previous promise, I asked for leave for the last semester before graduation and return back to Pingfeng. This time, I have been a volunteer teacher in Pingfeng Middle School to engage more into their study. During my volunteer experience, more and more friends of mine saw how poor it is and how incredible living condition there and come to join us to sponsor a child there.  When I return back to Cornell, I developed 21 sponsorship there, covering each class in 7th and 8th grade. Besides sponsorship, I also raise fund to donate each class a set of encyclopedia, putting in their little classroom corner libraries in each class for children to borrow.
    </p>
    <p>Our story is still continuing, there will never be an end.
    </p>
    <p><i>By: Amy Da, Founder of XiaoShu</i></p>
    

    <h1>Our vision</h1>
    <p>Xiaoshu is trying to helping more poverty  children for their education gradually with the mind trivial, but consistent; interaction more than finance support; and being earnest and constant.
    </p>
    <h2>Trivial, but consistent.
    </h2>
    <p>Contributions might be trivial each time, but please insist. Instead of overloading yourself by sending expensive gifts or taking dramatical efforts, we expect your contribution to be valuable, helpful and consistent.
    </p>
    <h2>Connections and interactions are more than financial support.
    </h2>
    <p>Between children and us, we treat each other as friends or even family members. In this type of relationship, our responsibilities are more about mentoring them. Other than providing financial support, we, as mentors, establish mental connection and interaction. Through mails, we encourage them to face difficulties, guide them to become mature and help them to open their minds.
    </p>
    <h2>We grow together.
    </h2>
    <p>We grow together, which is our key. In other words, we, as sponsors, are equivalent rather than superior to these children. These children are usually more considerate and mature due to special experiences and environments. Some of them are taking responsibilities as grown-ups despite their ages. We, who grew up in warm and comfortable incubators, can absolutely learn tremendously from them.
    </p>
    <h2>Be earnest and constant.
    </h2>
    <p>What we focus on is not how many children get sponsored every year, but instead how much cares and helps each child gain and whether these connections can last long.
    </p>
    
    <h1>Our name</h1>
    <p><b>Xiaoshu</b> is a Chinese phrase meaning a young tree. We selected it as the emblem of our website because what it suggests wonderfully suits our belief and principles. First, a young tree keeps growing no matter how little and slow that procedure is, which is quite similar to our belief that our help might be minor but consistent for poverty children education. On the other hand, a tree in it teenage is full of energy but presents tranquilly. Analogously, what we are doing are nuance and peaceful, not so impressive to be known by majority but tremendously energetic. Finally, I hope everyone standing under our tree can feel the love and warmness. We are friends, family rather than sponsors and serving object. We grow simultaneously and accompany each other eternally. It is the nature of hour human beings.
    </p>
  </div>
</div>

app/views/pages/contact.html.erb
<% content_for :css do %>
<style>

</style>
<% end %>

<div id="content">
  <div id="contact-bg" data-parallax="scroll" data-image-src="<%= asset_path('contactbg.jpg')%>" >
    <div class="container page-caption-container"> 
      <div class="caption-content">
        <div id="contact-title-container" class="page-title-container">
          <p class="page-title">KEEP IN TOUCH</p>
        </div>
      </div>
    </div>
  </div>
  <div class="page-content-section container">
    <% if @message_sent == true %>
      <h1>Thank you for your message!</h1>
      <h2>Your message has been submitted successfully! We will follow up with you for more information.</h2>
      <%=link_to 'Back to home', '/', :class => "btn-back-to-home btn btn-primary btn-lg"%>
    <% else %>
      <div class='col-lg-8 col-md-8 col-xs-12'>
        <h1>We are listening</h1>
        <div>
          <% flash.each do |key, value| %>
            <div>
              <a href="#" data-dismiss="alert">×</a>
                <%= value %>
            </div>
          <% end %>
        </div>
        <%= simple_form_for @message, :url => send_message_path, :html => {:class => 'contact-form' } do |f| %>
          <%= f.input :name, :required => true %>
          <%= f.input :email, :required => true %>
          <%= f.input :message, :as => :text, :required => true %>
          <div class= "hidden">
            <%= f.input :nickname, :hint => 'Leave this field blank!' %>
          </div>
          <div>
            </br>
            <%= f.button :submit, 'Send', :class=> "btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <div class="col-xs-12 col-md-4 col-lg-4" id="contact-other-container">
        <p>Or find us here:</p>
        
      </div>
    <% end %>
    
  </div>
</div>

app/views/pages/home.html.erb
<div id="content">
  <div id="first-bg" class="hero-bg full-height" data-parallax="scroll" data-image-src="<%= asset_path('Landing.jpg') %>">
    <div class="container caption-container"> 
      <div class="caption-content">
        <p class="text-title">XIAOSHU</p>
        <div class="subtitle-container">
          <p class="text-subtitle"><i>Poverty never hampers education</i></p>
        </div>
      </div>
    </div>
    <div id="scrolldown"><%= image_tag("chevron.png" ,:id => "chevron", :class => "animated", :alt => "Scrolldown") %></div>
  </div>
  <div id="intro-section" class="content-section container">
    <%= image_tag("xiaoshulogo.png" ,:id => "large-logo", :alt => "XiaoShu") %>
    <p id="text-intro">XiaoShu is a platform providing you a chance to help children in China's proverty areas continue their education.</p>
    <%=link_to 'READ OUR STORY AND VISION', 'about', :class => "btn btn-primary btn-lg"%>
  </div>
  <div id="second-bg" class="active-bg" data-parallax="scroll" data-image-src="<%= asset_path('Landing4.jpg') %>">
    <div id="second-caption" class="caption-container container"> 
      <div id="second-caption-content" class="col-md-7 col-xs-12">
        <p class="text-impression"><i>"XiaoShu made my life more meaningful by helping XXX achieve her college dream."<br>-XiaoShu Sponsor: YYY</i></p>
      </div>
    </div>
  </div>
  <div id="program-section" class="content-section container">
    <div class="program-char-container col-md-4 col-xs-12">
      <%= image_tag("icon1.png",:id => "program-illu-1", :class => 'program-illu') %>
      <p class="program-char-title">1 to 1 Sponsorship</p>
      <p class="program-char">Matched with the child you sponsor.<br> Knowing exactly who you are helping.</p>
    </div>
    <div class="program-char-container col-md-4 col-xs-12">
      <%= image_tag("Picture4.png",:id => "program-illu-2", :class => 'program-illu') %>
      <p class="program-char-title">Direct Connection</p>
      <p class="program-char">Transfering funds directly to the child.<br> Knowing where your money is going.</p>
    </div>
    <div class="program-char-container col-md-4 col-xs-12">
      <%= image_tag("Picture5.png",:id => "program-illu-3", :class => 'program-illu') %>
      <p class="program-char-title">More than a Sponsor</p>
      <p class="program-char">Building deep connection with children.<br> Providing guidance and mentorship.</p>
    </div>
    <%=link_to 'KNOW OUR SPONSORSHIP PROGRAM', 'program', :class => "btn btn-primary btn-lg"%>
  </div>
  <div id="third-bg" class="active-bg" data-parallax="scroll" data-image-src="<%= asset_path('Landing3.jpg') %>">
    <div id="third-caption" class="caption-container container"> 
      <div id="third-caption-content" class="col-lg-7 col-md-9 col-sm-12 col-xs-12">
        <p class="text-gallery">Photos never lie. We are doing it!</p>
      </div>
    </div>
  </div>
  <div id="gallery-section" class="content-section container">
    <div id="gallery-photo-container" class="col-lg-11 col-xs-12">
      <% for i in 1..15 %>
        <div class="gallery-photo" image="image<%= i.to_s %>" id="gallery-photo-<%= i.to_s %>"></div>
        <%= image_tag("xiaoshugallery/image"+i.to_s+'.jpg',:id => "image"+i.to_s, :class => 'hidden gallery-img') %>
      <% end %>
    </div>
    <div class="col-xs-12">
      <%=link_to 'BECOME A SPONSOR NOW', 'join', :id => 'btn-become-sponsor', :class => "btn btn-primary btn-lg"%>
    </div>
  </div>
</div>

app/views/pages/join.html.erb
<% content_for :css do %>
<style>

</style>
<% end %>

<div id="content">
  <div id="join-bg" data-parallax="scroll" data-image-src="<%= asset_path('joinbg.jpg')%>" >
    <div class="container page-caption-container"> 
      <div class="caption-content">
        <div id="join-title-container" class="page-title-container">
          <p class="page-title">JOIN OUR SPONSORSHIP PROGRAM</p>
        </div>
      </div>
    </div>
  </div>
  <div class="page-content-section container">
    <% if @application_sent == true %>
      <h1>Thank you for your interest!</h1>
      <h2>Your application has been submitted successfully! We will follow up with you for more information.</h2>
      <%=link_to 'Back to home', '/', :class => "btn-back-to-home btn btn-primary btn-lg"%>
    <% else %>
      <div class='col-lg-8 col-md-8 col-xs-12'>
        <h1>We just want to know more about you...</h1>
        <div>
          <% flash.each do |key, value| %>
            <div>
              <a href="#" data-dismiss="alert">×</a>
                <%= value %>
            </div>
          <% end %>
        </div>
        <%= simple_form_for @application, :url => send_application_path, :html => {:class => 'join-form' } do |f| %>
          <%= f.input :name, :required => true %>
          <%= f.input :email, :required => true %>
          <%= f.input :personal_website_or_profile, :required => false%>
          <%= f.input :intro_about_yourself, :as => :text, :required => true %>
          <div class= "hidden">
            <%= f.input :nickname, :hint => 'Leave this field blank!' %>
          </div>
          <div>
            </br>
            <%= f.button :submit, 'Submit', :class=> "btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <div class="col-xs-12 col-md-4 col-lg-4" id="join-question-container">
        <p>Not sure about how the program works?</p>
        <%=link_to 'Learn more about it', 'program', :class => "btn btn-primary"%>
      </div>
    <% end %>
    
  </div>
</div>

app/views/pages/program.html.erb
<% content_for :css do %>
<style>

</style>
<% end %>

<div id="content">
  <div id="program-bg" data-parallax="scroll" data-image-src="<%= asset_path('programbg.jpg')%>" >
    <div class="container page-caption-container"> 
      <div class="caption-content">
        <div id="program-title-container" class="page-title-container">
          <p class="page-title">GIVE MORE &#8226; GAIN MORE</p>
        </div>
        <%=link_to 'Become a sponsor', 'join',:class => "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="page-content-section container">
    <div class="col-xs-12">
      <h1>How does it work? (Coming soon)</h1>
    </div>
    <div class='col-md-7 col-xs-12'>
      <%= image_tag("programdiagram.png" ,:id => "program-illustration") %>
    </div>
    <div class='col-md-5 col-xs-12'>
      <ul id="program-bullets">
        <li>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </li> 
        <li>
          Aenean euismod bibendum laoreet.
        </li> 
        <li>
          Proin gravida dolor sit amet lacus accumsan et viverra justo commodo.
        </li> 
        <li>
          Proin sodales pulvinar tempor.
        </li> 
        <li>
          Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        </li> 
      </ul>
      <div class="container-fluid" id="download-link-container">
        <%=link_to 'Download full document (PDF)', '#', :id => 'btn-download-doc', :class => "disabled btn btn-primary"%>
        <br>(Coming soon)
      </div>
    </div>
    <div class="col-xs-12">
      <h1>Our sponsors think...(Coming soon)</h1>
    </div>
    <div class="col-xs-12 col-md-4 avatar-container">
      <%= image_tag("avatar.png" ,:class => "sponsor-avatar") %>
      <p class="sponsor-name">Toro Gu</p>
      <p class="quote-content">"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. "
      </p>
    </div>
    <div class="col-xs-12 col-md-4 avatar-container">
      <%= image_tag("avatar.png" ,:class => "sponsor-avatar") %>
      <p class="sponsor-name">Sissi Yu</p>
      <p class="quote-content">"Proin gravida dolor sit amet lacus accumsan et viverra justo commodo."</p>
    </div>
    <div class="col-xs-12 col-md-4 avatar-container">
      <%= image_tag("avatar.png" ,:class => "sponsor-avatar") %>
      <p class="sponsor-name">Landy Zhu</p>
      <p class="quote-content">"Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo."</p>
    </div>
    <div class="col-xs-12" id="btn-become-sponsor-program">
      <%=link_to 'Become a sponsor now', 'join',:class => "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>